version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true