[package]
name = "fire_seq_search_server"
version = "0.1.2"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Http Client
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde_json = "1.0"
# Serde
#   https://serde.rs/derive.html
#   https://stackoverflow.com/a/49313680/1166518
serde = { version = "1.0", features = ["derive", "rc"] }
url = "2.3.1"

# QueryEngine
tantivy = "0.18"


log = "0.4.0"
env_logger = "0.9.0"

# Rust
clap = { version = "4.0", features = ["derive"] }
lazy_static = "1.4.0"
rayon = "1.5"

urlencoding = "2.1.0"
jieba-rs = { version = "0.6.6" }


stopwords = "0.1.1"

regex = "1"
lingua = { version = "1.4.0", default-features = false, features = ["chinese", "english"] }

# Parsing
pulldown-cmark = { version = "0.9.2", default-features = false }
pdf-extract = "0.6.4"
lopdf = { version = "0.29", default-features = false, features = [ "pom_parser" ] }