[package]
name = "fire_seq_search_server"
version = "0.0.9"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
tantivy = "0.16.1"
log = "0.4.0"
env_logger = "0.9.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] } # https://serde.rs/derive.html
clap = { version = "3.0.14", features = ["derive"] }
urlencoding = "2.1.0"
cang-jie = "0.13.0"
jieba-rs = { version = "0.6.6" }
lazy_static = "1.4.0"
