[package]
name = "fire_seq_search_server"
version = "0.0.21"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Http Client
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] } # https://serde.rs/derive.html

# Search Engine
tantivy = "0.18"


log = "0.4.0"
env_logger = "0.9.0"

# Rust
clap = { version = "4.0", features = ["derive"] }


urlencoding = "2.1.0"
jieba-rs = { version = "0.6.6" }
lazy_static = "1.4.0"
rayon = "1.5"
stopwords = "0.1.1"
pulldown-cmark = { version = "0.9.2", default-features = false }
regex = "1"
lingua = { version = "1.4.0", default-features = false, features = ["chinese", "english"] }
