name: Quality Control
on: [push, pull_request]
jobs:
  cargo-deny:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v2
    - name: Install Rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
    - name: Install cargo deny
      continue-on-error: true
      run: |
          cargo install --locked cargo-deny
          cd fire_seq_search_server
          cargo deny init
          cargo deny check

    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
    - name: clippy
      run: |
          cd fire_seq_search_server
          rustup component add clippy
          cargo clippy
